### ISSUE TITLE
Фикс Malborasek

### ISSUE THREAD

**Issue by h4rtley** [ajioe1111/Mods-Project-Baro-RP#2]
- [x] Перенести Afflictions с Creatures в Other Items
- [x] Починить BrokenSprite
- [x] Починить Misc.png
- [ ] Починить выдачу Зависимости

**Comment by h4rtley** [comment]
![image](https://user-images.githubusercontent.com/95498021/163625015-986f1bcd-9b1a-4897-be85-e62b6bdfb9fb.png)
_Я без понятия, как это может быть "закончено" по словам одного человека. Всё поломано!_

**Comment by ajioe1111** [comment]
Двойной путь может быть ещё из-за символа \ вместо /
Проверить надо.

**Comment by ajioe1111** [comment]
Символ / указывает путь от начальной точки, то-есть из папки Mods
Символ \ указывает путь относительно исполняющего .xml файла

**Comment by h4rtley** [comment]
> Двойной путь может быть ещё из-за символа \ вместо / Проверить надо.

Сами сломанные спрайты написаны через /
Но ладно, попробую что-нибудь с этим сделать.
В крайнем случае - обрежу спрайты скуренной сигареты

**Comment by ajioe1111** [comment]
![image](https://user-images.githubusercontent.com/39803571/163626724-0d0f6153-48c2-4940-9dcb-f10beb8e3578.png)

**Comment by h4rtley** [comment]
Так. Погодьте. Я уже не ориентируюсь в файлах

**Comment by h4rtley** [comment]
Afflictions не связаны с BrokenSprites
![image](https://user-images.githubusercontent.com/95498021/163627039-134b53af-1e0e-45ed-aa51-5196f0c8fbda.png)
