### ISSUE TITLE
Вход в стабильный режим.

### ISSUE THREAD

**Issue by ajioe1111** [ajioe1111/Mods-Project-Baro-RP#3]
Новая задача на всех.
@ajioe1111 @h4rtley @Raizlen

До **22.04.2022** нужно подготовить beta ветку для перехода в релиз.

- [x] Закончить текущие работы.
- [x] Убедиться в работоспособности.
- [x] Сделать merge beta ветки и master ветки.

Это нужно сделать так как на текущий момент не имеется возможным обновить моды в воркшопе.

> Я так же напомню про это #1

**Comment by h4rtley** [comment]
Как там дела у Смита?

**Comment by ZackEsakovZombiezzz** [comment]
Именные вещи по идее стабильны вот стартовые рандомные болезни

**Comment by ajioe1111** [comment]
Из-за обновления планирую сделать ветку раньше времени, всё готово?
