### ISSUE TITLE
Спрайты ликвидаторов

### ISSUE THREAD

**Issue by h4rtley** [ajioe1111/Mods-Project-Baro-RP#4]
Отсутствуют спрайты в инвентаре

**Comment by ajioe1111** [comment]
Если они физически есть, то достаточно зайти в игру и вбить в консоль spriteeditor

**Comment by h4rtley** [comment]
Айка, скажи, кто-нибудь редактировал .png с спрайтами? Я вот ещё покуда нет, да и ты вряд-ли тоже

**Comment by ajioe1111** [comment]
Спрайты брони я не трогала. Не думаю что @Raizlen что-то с ними делал.

**Comment by h4rtley** [comment]
Нужно редачить InventoryIcons и MiscJobGear

**Comment by h4rtley** [comment]
И нет, там ничего нового

**Comment by ajioe1111** [comment]
Время закончить есть 😘

**Comment by h4rtley** [comment]
И то верно. Может протащу в мод ещё одну песню, а может и амулет 🙃

**Comment by ajioe1111** [comment]
Главное помните про создание задач. Так проще ориентироваться кто над чем работает.
