### ISSUE TITLE
Tasklist Хартли

### ISSUE THREAD

**Issue by h4rtley** [ajioe1111/Mods-Project-Baro-RP#5]
Основная работа:

Второй план:
- [ ] Майкл Прайс как персонаж
- [ ] Перенос маяков в мод (?)
- [ ] Перенос части Saber Personal Protection Revived в мод

Hopes and dreams:
- [ ] А тут что-то должно быть?

**Comment by ajioe1111** [comment]
Актуально?

**Comment by h4rtley** [comment]
А хрен знает. Кассеты уже сделал, а остальное - уже хрен с этим
