### ISSUE TITLE
Переделка модов.

### ISSUE THREAD

**Issue by ajioe1111** [ajioe1111/Mods-Project-Baro-RP#8]
Обновление конечно всё нахер сломало, но и внесло порядок. Теперь будет проще заниматься модингом.
На этом фоне временно приостанавливаем работы над модами.
Сейчас я начинаю заниматься реорганизацией модов.

- [ ] Выкинуть старое и ненужное.
- [ ] Внести фиксы в то что уже есть.
- [ ] Объединить моды в один.
- [ ] Провести тест на работоспособность.
- [ ] Выйти в релиз.

**Comment by ajioe1111** [comment]
Планы немного изменились.
Теперь мы переходим на ядро (corepackage).

**Comment by h4rtley** [comment]
А чего?

**Comment by h4rtley** [comment]
У нас и так 3 мода под свою категорию. Всё в одну кучу снова скидывать будем?

**Comment by ajioe1111** [comment]
Мы теперь будем работать с набором контента
